### ISSUE TITLE
Inject SVG Symbols

### ISSUE THREAD

**Issue by monicat112** [gravityworks/startercss#1]
Add a Gulp task to write _the compiled_ SVG symbols file into an _html_ file whenever there's an icon change.

Edit: clarification

**Comment by theleewise** [comment]
I just tried and this seems to be working. Steps I took for it to work:

1. Clone Repo
2. Run 'npm install'
3. Run 'gulp' or 'gulp watch'
4. Drop new svg file in 'source/svg-icons/' or rename an svg file in that directory or delete an svg file in that directory

Can someone else try?

**Comment by monicat112** [comment]
That part works fine. I meant something different, but reading the post again I could have been more clear about it, sorry.

What I mean is that we should have a task that can copy the contents of the compiled svg into an html file. I'm currently copy/pasting the svg any time it's updated.
